export const workshopExtended = [
    {
        id: 1,
        city: "Bilbao",
        activity: "Acuarela Botánica",
        month: "Mayo",
        price: "50€",
        center: "Manos Creativas",
        places: 8,
        descShort: "Pinta flores sin que parezcan manchas de café.",
        descLarge: "La acuarela premia la paciencia. Trabajaremos capas de transparencia, control del agua y cómo dejar que el pigmento fluya solo. Ideal para ilustrar tu propio herbario o simplemente relajarte viendo cómo se mezcla el color.",
        randomFact: "La acuarela es el único deporte de riesgo donde el mayor peligro es beberte el agua del pincel por error."
    },
    {
        id: 2,
        city: "Madrid",
        activity: "Cerámica al Torno",
        month: "Junio",
        price: "65€",
        center: "Barro Terapia",
        places: 6,
        descShort: "Como en Ghost, pero con menos Patrick Swayze y más barro en la cara.",
        descLarge: "Enfrentarse al torno requiere fuerza y delicadeza. Aprenderás a centrar el barro, abrir la pella y levantar paredes para crear tu propia taza o cuenco. Incluye el horneado de las piezas.",
        randomFact: "Si la pieza se tambalea demasiado, di que es 'movimiento orgánico'. Cuela siempre ante las visitas."
    },
    {
        id: 3,
        city: "Barcelona",
        activity: "Tufting de Alfombras",
        month: "Julio",
        price: "85€",
        center: "The Rug Club",
        places: 4,
        descShort: "Dispara lana para crear tu propia alfombra peluda.",
        descLarge: "Usa una tufting gun industrial para insertar hilos de lana en una tela tensada. Diseñaremos un patrón geométrico y lo rellenaremos a toda velocidad. Es ruidoso, rápido y extremadamente satisfactorio.",
        randomFact: "El sonido de la máquina de tufting es el ASMR definitivo para los adictos a las manualidades modernas."
    },
    {
        id: 4,
        city: "Valencia",
        activity: "Cianotipia",
        month: "Mayo",
        price: "45€",
        center: "Luz Azul Studio",
        places: 12,
        descShort: "Fotografía con el sol. Magia química para nostálgicos.",
        descLarge: "Utilizaremos sales férricas para sensibilizar papel y exponerlo a la luz UV. El resultado son imágenes en un azul Prusia intenso. Usaremos plantas secas y negativos de fotos antiguas.",
        randomFact: "Anna Atkins, la primera mujer fotógrafa, usó esta técnica para crear el primer libro de ilustraciones botánicas de la historia."
    },
    {
        id: 5,
        city: "Sevilla",
        activity: "Bordado de Frases",
        month: "Agosto",
        price: "40€",
        center: "Puntadas Rebeldes",
        places: 10,
        descShort: "Borda lo que no te atreves a decir en voz alta.",
        descLarge: "Aprenderás puntos básicos de contorno y relleno. Olvida los manteles clásicos; aquí bordamos letras con estilo graffiti o frases motivadoras (o sarcásticas) sobre lino.",
        randomFact: "Pincharse con la aguja forma parte del proceso de iniciación. Es el tributo que exige el dios del hilo."
    },
    {
        id: 6,
        city: "Granada",
        activity: "Macramé",
        month: "Octubre",
        price: "35€",
        center: "Nudos y Caos",
        places: 15,
        descShort: "Hacer nudos hasta que te olvides de tus problemas.",
        descLarge: "Crearemos un colgador de plantas usando nudos decorativos. Trabajaremos con cuerda de algodón reciclado de 4mm. Aprenderás el nudo plano, el alondra y el festón.",
        randomFact: "Los marineros vendían sus trabajos de macramé en los puertos, convirtiéndose en los primeros influencers del DIY del siglo XIX."
    },
    {
        id: 7,
        city: "Málaga",
        activity: "Kokedamas",
        month: "Septiembre",
        price: "55€",
        center: "Selva Urbana",
        places: 8,
        descShort: "Plantas que viven en una bola de musgo. Sin macetas.",
        descLarge: "Aprenderás la técnica japonesa de envolver raíces en una mezcla de tierra akadama y turba, sellándolo todo con musgo vivo e hilo. Una forma escultórica de tener plantas en casa.",
        randomFact: "Es la técnica ideal para los que tienen poco espacio y mucha fe en que la planta sobreviva a su dueño."
    },
    {
        id: 8,
        city: "Zaragoza",
        activity: "Punch Needle",
        month: "Noviembre",
        price: "48€",
        center: "Aguja Veloz",
        places: 10,
        descShort: "El primo gordito y divertido del bordado tradicional.",
        descLarge: "Usaremos una aguja mágica para crear bucles de lana sobre tela de monje. Es una técnica muy rápida que permite crear texturas con relieve tipo toalla.",
        randomFact: "Es como colorear con lana, pero si te equivocas, solo tienes que tirar del hilo y empezar de nuevo sin dejar rastro."
    },
    {
        id: 9,
        city: "Murcia",
        activity: "Lettering con Pincel",
        month: "Abril",
        price: "30€",
        center: "Tinta y Letras",
        places: 20,
        descShort: "Dibuja letras para que tu caligrafía deje de ser un jeroglífico.",
        descLarge: "Dominaremos el brush pen. Practicaremos trazos finos ascendentes y gruesos descendentes para crear alfabetos elegantes. Perfecto para tarjetas y cartelería.",
        randomFact: "La clave del lettering es que no estás escribiendo, estás dibujando. Así que no importa si tienes letra de médico."
    },
    {
        id: 10,
        city: "Valladolid",
        activity: "Encuadernación Japonesa",
        month: "Diciembre",
        price: "42€",
        center: "Papel y Cuerda",
        places: 12,
        descShort: "Cose tus propias libretas con costuras vistas espectaculares.",
        descLarge: "Encuadernaremos hojas sueltas usando la técnica de 'cuatro agujeros'. Es una costura artesanal que queda por fuera de las tapas, dándole un acabado artístico y profesional.",
        randomFact: "Esta costura es tan bonita que te dará mucha pena escribir en la libreta. Acabará en una estantería cogiendo polvo estético."
    },
    {
        id: 11,
        city: "Vigo",
        activity: "Joyas en Resina",
        month: "Junio",
        price: "50€",
        center: "Gema Creativa",
        places: 8,
        descShort: "Encapsula flores, purpurina o tus sueños frustrados.",
        descLarge: "Aprenderás a mezclar resina epoxi de dos componentes, a eliminar burbujas y a usar moldes de silicona para crear pendientes y colgantes únicos con elementos botánicos.",
        randomFact: "Trabajar con resina es 10% creatividad y 90% rezar intensamente para que no queden burbujas de aire justo en el centro."
    },
    {
        id: 12,
        city: "Palma de Mallorca",
        activity: "Estampación con Sellos",
        month: "Julio",
        price: "38€",
        center: "Estampa Mar",
        places: 14,
        descShort: "Talla tus propios sellos de goma y llena todo de tinta.",
        descLarge: "Usaremos gubias para tallar diseños en planchas de goma blanda. Después estamparemos sobre papel y tela usando tintas de colores vibrantes.",
        randomFact: "Cualquier objeto es un sello potencial si tienes suficiente imaginación y poca vergüenza frente a los materiales."
    },
    {
        id: 13,
        city: "Pamplona",
        activity: "Puntillismo en Mandalas",
        month: "Octubre",
        price: "35€",
        center: "Zen Art",
        places: 15,
        descShort: "Puntos infinitos para una paciencia infinita.",
        descLarge: "Decoraremos piedras de río o lienzos circulares usando herramientas de puntos (dotting tools). Es un ejercicio de concentración y geometría visual muy relajante.",
        randomFact: "Se recomienda respirar entre punto y punto. La hipnosis colectiva por exceso de concentración está incluida en el precio."
    },
    {
        id: 14,
        city: "Alicante",
        activity: "Velitas de Soja",
        month: "Marzo",
        price: "45€",
        center: "Luz y Aroma",
        places: 10,
        descShort: "Haz que tu casa huela a paraíso y no a gimnasio.",
        descLarge: "Fundiremos cera de soja natural, añadiremos aceites esenciales y decoraremos con flores secas. Aprenderás las temperaturas de vertido para que la superficie quede perfecta.",
        randomFact: "La cera de soja es biodegradable, así que técnicamente eres un héroe del medio ambiente por fabricar velas."
    },
    {
        id: 15,
        city: "Gijón",
        activity: "Ilustración Digital",
        month: "Septiembre",
        price: "60€",
        center: "Pixel Studio",
        places: 12,
        descShort: "Aprende a usar Procreate sin que el iPad acabe volando.",
        descLarge: "Taller para principiantes donde veremos el uso de capas, pinceles dinámicos y máscaras de recorte. Trae tu tablet y sal con una ilustración terminada.",
        randomFact: "El comando 'Deshacer' con dos dedos es la mejor invención de la humanidad después de la rueda y el WiFi."
    },
    {
        id: 16,
        city: "A Coruña",
        activity: "Cocina de Fermentados",
        month: "Abril",
        price: "55€",
        center: "Fermento Lab",
        places: 10,
        descShort: "Kombucha y Kimchi: haz que las bacterias trabajen para ti.",
        descLarge: "Entenderemos el mundo de la fermentación láctica. Prepararemos nuestro propio tarro de verduras fermentadas y aprenderemos a cuidar de una 'madre' de kombucha.",
        randomFact: "Si algo burbujea y no huele a alcantarilla olvidada, ¡vas por muy buen camino en la fermentación!"
    },
    {
        id: 17,
        city: "Toledo",
        activity: "Cestería Moderna",
        month: "Mayo",
        price: "48€",
        center: "Mimbre y Tradición",
        places: 8,
        descShort: "Teje cestos con fibras naturales. Muy rústico, muy chic.",
        descLarge: "Usaremos médula de mimbre mojada para que sea flexible. Aprenderás el tejido básico de base y cómo subir las guías para dar forma a un cesto utilitario.",
        randomFact: "Es la actividad favorita de los que quieren vivir en una cabaña en el bosque pero necesitan fibra óptica de 1GB."
    },
    {
        id: 18,
        city: "Burgos",
        activity: "Jabones Artesanales",
        month: "Noviembre",
        price: "40€",
        center: "Burbuja Pura",
        places: 12,
        descShort: "Huele a limpio, luce como un auténtico alquimista.",
        descLarge: "Haremos jabones por el método de glicerina y técnica de 'marmolado'. Añadiremos arcillas y exfoliantes naturales como semillas de amapola.",
        randomFact: "Hacer jabón es como cocinar, pero si te equivocas de ingrediente, en vez de cena tienes un desastre químico espumoso."
    },
    {
        id: 19,
        city: "San Sebastián",
        activity: "Collage Analógico",
        month: "Agosto",
        price: "30€",
        center: "Recorta y Pega",
        places: 20,
        descShort: "Recorta revistas viejas y crea mundos surrealistas.",
        descLarge: "Exploraremos la composición visual usando solo tijeras, pegamento y material impreso antiguo. No hace falta saber dibujar, solo tener buen ojo para mezclar conceptos.",
        randomFact: "El pegamento de barra es el mejor amigo del hombre, seguido muy de cerca por el perro y el café de especialidad."
    },
    {
        id: 20,
        city: "Logroño",
        activity: "Origami Gigante",
        month: "Enero",
        price: "35€",
        center: "Papel Plegado",
        places: 15,
        descShort: "Dobla papel hasta que parezca arte o un avión frustrado.",
        descLarge: "Llevaremos el origami a gran escala. Crearemos figuras geométricas XL para decoración de eventos usando papeles de alto gramaje.",
        randomFact: "El récord mundial de pliegues en un papel es 12. Aquí con que hagas una grulla que se sostenga nos conformamos."
    },
    {
        id: 21,
        city: "Córdoba",
        activity: "Terrarios cerrados",
        month: "Abril",
        price: "60€",
        center: "Ecosistema Mini",
        places: 6,
        descShort: "Crea un mundo dentro de un bote de cristal.",
        descLarge: "Aprenderás a crear las capas de drenaje, carbón activo y sustrato para que tus plantas respiren dentro de un bote hermético. Es un ciclo de agua autosuficiente.",
        randomFact: "Un terrario bien hecho puede durar años sin regarse. Es el regalo perfecto para los 'serial killers' de plantas."
    },
    {
        id: 22,
        city: "Santander",
        activity: "Cata y Pintura",
        month: "Febrero",
        price: "50€",
        center: "Arte con Vino",
        places: 18,
        descShort: "Pintar es mucho mejor con una copa en la mano.",
        descLarge: "Un taller social donde pintaremos un cuadro paso a paso mientras catamos tres vinos locales. El objetivo es divertirse, no ganar el Premio Velázquez.",
        randomFact: "A partir de la tercera copa, todos los cuadros parecen obras maestras de Van Gogh. Es un fenómeno científico probado."
    },
    {
        id: 23,
        city: "Salamanca",
        activity: "Crochet Amigurumi",
        month: "Marzo",
        price: "38€",
        center: "Ganchillo Club",
        places: 12,
        descShort: "Haz un muñeco de ganchillo que no asuste a los niños.",
        descLarge: "Aprenderás el anillo mágico, el punto bajo y cómo hacer aumentos y disminuciones para dar forma a un pequeño animal de peluche.",
        randomFact: "El crochet es el yoga de las manos, aunque a veces acabas con una bufanda de 4 metros por no saber cuándo parar."
    },
    {
        id: 24,
        city: "Almería",
        activity: "Fotografía con Móvil",
        month: "Junio",
        price: "30€",
        center: "Click Academy",
        places: 25,
        descShort: "Haz fotones sin necesidad de una cámara de 3000€.",
        descLarge: "Hablaremos de composición, la regla de los tercios y cómo editar tus fotos con apps gratuitas para que parezcan profesionales.",
        randomFact: "El 90% de una buena foto con móvil consiste en limpiar la lente con la camiseta justo antes de disparar."
    },
    {
        id: 25,
        city: "Badajoz",
        activity: "Upcycling Textil",
        month: "Mayo",
        price: "45€",
        center: "Segunda Vida",
        places: 10,
        descShort: "Convierte esos vaqueros viejos en algo increíble.",
        descLarge: "Trae ropa que ya no uses. Aprenderemos a cortar y ensamblar piezas para crear bolsos, fundas de cojín o parches decorativos estilo patchwork.",
        randomFact: "No lo llames basura, llámalo 'material vintage con alto potencial creativo' para sonar más profesional."
    },
    {
        id: 26,
        city: "Castellón",
        activity: "Escultura con Alambre",
        month: "Julio",
        price: "42€",
        center: "Líneas de Metal",
        places: 10,
        descShort: "Dibuja en el aire usando hilo de metal.",
        descLarge: "Usaremos alambre de diferentes grosores para crear figuras minimalistas en 3D. Es como dibujar con lápiz, pero en el espacio real.",
        randomFact: "Cuidado: el alambre tiene memoria y vida propia; tiende a querer saltarte a la cara si no lo sujetas con firmeza."
    },
    {
        id: 27,
        city: "Tarragona",
        activity: "Teñido Shibori",
        month: "Septiembre",
        price: "48€",
        center: "Índigo Taller",
        places: 12,
        descShort: "El Tie-dye japonés que es elegante y no hippie.",
        descLarge: "Doblaremos y bloquearemos la tela con maderas y pinzas antes de sumergirla en un tinte azul índigo para crear patrones geométricos preciosos.",
        randomFact: "El tinte índigo es tan potente que podrías tener las uñas azules hasta la próxima Navidad si no usas guantes."
    },
    {
        id: 28,
        city: "Lugo",
        activity: "Patchwork Moderno",
        month: "Noviembre",
        price: "50€",
        center: "Retales Lab",
        places: 10,
        descShort: "Cose trozos de tela para crear algo mucho más grande.",
        descLarge: "Aprenderás a cortar piezas exactas y a unirlas para crear un bloque de diseño contemporáneo que servirá de base para una manta o cojín.",
        randomFact: "El patchwork es como el Tetris, pero si pierdes, al menos tienes una manta calentita para pasar el disgusto."
    },
    {
        id: 29,
        city: "Ourense",
        activity: "Cosmética Sólida",
        month: "Octubre",
        price: "55€",
        center: "Bio Belleza",
        places: 12,
        descShort: "Champús y cremas sin plástico. Planeta feliz.",
        descLarge: "Formularemos un champú sólido y un bálsamo labial usando mantecas vegetales y tensioactivos suaves derivados del coco.",
        randomFact: "Hacer tu propio champú te da el superpoder de entender por fin qué significan los ingredientes de los botes del súper."
    },
    {
        id: 30,
        city: "Gerona",
        activity: "Galletas Decoradas",
        month: "Diciembre",
        price: "40€",
        center: "Dulce Arte",
        places: 15,
        descShort: "Pinta con glasa real. Arte que se puede comer.",
        descLarge: "Aprenderás a hacer la consistencia perfecta de la glasa para delinear y rellenar galletas con diseños navideños o florales.",
        randomFact: "El mayor reto de este taller no es el dibujo, es resistir la tentación de comerse los materiales antes de terminar."
    },
    {
        id: 31,
        city: "Huelva",
        activity: "Mosaico Moderno",
        month: "Marzo",
        price: "45€",
        center: "Teselas de Luz",
        places: 10,
        descShort: "Rompe cosas para construir algo nuevo. Terapéutico.",
        descLarge: "Cortaremos azulejos de colores para crear un diseño sobre una base de madera. Aprenderás a usar la tenaza de alicatador y a dar el rejuntado final.",
        randomFact: "Es la mejor forma de soltar estrés. Romper azulejos a martillazos es más barato y efectivo que ir al psicólogo."
    },
    {
        id: 32,
        city: "Lleida",
        activity: "Talla de Cucharas",
        month: "Febrero",
        price: "60€",
        center: "Madera Viva",
        places: 8,
        descShort: "Madera, un cuchillo y mucha calma. El taller más hipster.",
        descLarge: "A partir de un trozo de madera verde, usaremos hachuelas y cuchillos de talla para dar forma a una cuchara funcional. Un proceso lento y manual.",
        randomFact: "Empezarás queriendo hacer una cuchara sopera y podrías acabar con un palillo de dientes si te pasas tallando."
    },
    {
        id: 33,
        city: "Cáceres",
        activity: "Linograbado",
        month: "Abril",
        price: "42€",
        center: "Grabado Libre",
        places: 12,
        descShort: "Corta linóleo y estampa tus diseños en papel.",
        descLarge: "Tallaremos una matriz de linóleo, la entintaremos con rodillo y haremos una tirada de estampas usando una prensa manual.",
        randomFact: "Las gubias cortan mucho. La regla número uno es: 'Corta siempre hacia afuera', a menos que quieras un vendaje artístico."
    },
    {
        id: 34,
        city: "Jaén",
        activity: "Pintura sobre Seda",
        month: "Mayo",
        price: "55€",
        center: "Seda y Color",
        places: 8,
        descShort: "Colores vibrantes que fluyen sobre tela de lujo.",
        descLarge: "Usaremos tintas especiales y bastidores para tensar la seda. Aprenderás a usar la 'gutta' para delimitar las zonas y que el color no se escape.",
        randomFact: "La seda absorbe el color tan rápido que tienes que ser más veloz que el propio tinte para evitar manchas raras."
    },
    {
        id: 35,
        city: "Vitoria",
        activity: "Creación de Podcast",
        month: "Junio",
        price: "40€",
        center: "Onda Creativa",
        places: 10,
        descShort: "Tienes cosas que decir y nosotros te damos el micro.",
        descLarge: "Taller de guion, grabación básica y edición rápida. Aprenderás qué equipo necesitas para empezar tu propio programa desde casa.",
        randomFact: "Lo más difícil de un podcast no es grabarlo, es escuchar tu voz después sin querer mudarte de planeta."
    },
    {
        id: 36,
        city: "Las Palmas",
        activity: "Jardines Verticales",
        month: "Julio",
        price: "50€",
        center: "Pared Verde",
        places: 10,
        descShort: "Si no tienes suelo, usa las paredes. Verde por doquier.",
        descLarge: "Construiremos una estructura ligera para colgar plantas crasas y suculentas, ideales para crear un cuadro vivo en tu terraza.",
        randomFact: "Las plantas colgadas son más felices porque tienen mejores vistas del salón que las que están en el rincón del suelo."
    },
    {
        id: 37,
        city: "Tenerife",
        activity: "Sushimanía",
        month: "Agosto",
        price: "45€",
        center: "Roll & Art",
        places: 15,
        descShort: "Enrolla arroz como un auténtico profesional de Tokio.",
        descLarge: "Aprenderás a preparar el arroz (shari), a cortar el pescado y a usar la esterilla de bambú para hacer maki y uramaki perfectos.",
        randomFact: "El secreto está en el vinagre y en no apretar demasiado, o terminarás fabricando ladrillos de arroz en lugar de sushi."
    },
    {
        id: 38,
        city: "Cuenca",
        activity: "Escritura Creativa",
        month: "Septiembre",
        price: "30€",
        center: "Pluma Libre",
        places: 20,
        descShort: "Desbloquea tu mente y suelta la mano. Escribe ya.",
        descLarge: "Mediante disparadores creativos y juegos literarios, romperemos el miedo a la página en blanco para crear microrrelatos originales.",
        randomFact: "La página en blanco no muerde, solo te mira fijamente con aire de superioridad esperando a que te equivoques."
    },
    {
        id: 39,
        city: "Pontevedra",
        activity: "Papel Reciclado",
        month: "Octubre",
        price: "35€",
        center: "Eco Papel",
        places: 15,
        descShort: "Haz papel nuevo a partir de tus facturas viejas.",
        descLarge: "Trituraremos papel usado para crear pulpa, usaremos marcos con tamiz para formar hojas nuevas y las decoraremos con pétalos de flores.",
        randomFact: "Es muy satisfactorio destruir facturas de la luz para convertirlas en folios donde dibujar flores de colores."
    },
    {
        id: 40,
        city: "Segovia",
        activity: "Ukelele Express",
        month: "Noviembre",
        price: "50€",
        center: "Acordes Felices",
        places: 12,
        descShort: "Monta tu instrumento y aprende tus primeros acordes.",
        descLarge: "Un taller híbrido: ajustaremos las cuerdas de un ukelele básico y aprenderemos los 4 acordes mágicos con los que puedes tocar el 80% de las canciones pop.",
        randomFact: "El ukelele es el instrumento que suena alegre incluso cuando intentas tocar la canción más triste de la historia."
    }
];