export const workshopExtended = [
  {
    idExtended: 1,
    city: "Bilbao",
    activity: "Acuarela Botánica",
    act: "pintura",
    month: "Mayo",
    price: "55€",
    center: "Manos Creativas",
    places: 8,
    descShort: "Pinta flores sin que parezcan manchas de café.",
    descLarge: "La acuarela premia la paciencia. Trabajaremos capas de transparencia, control del agua y cómo dejar que el pigmento fluya solo. Ideal para ilustrar tu propio herbario.",
    randomFact: "La acuarela es el único deporte de riesgo donde el mayor peligro es beberte el agua del pincel por error."
  },
  {
    idExtended: 2,
    city: "Bilbao",
    activity: "Kintsugi para Torpes",
    act: "ceramica",
    month: "Junio",
    price: "65€",
    center: "Barro y Alma",
    places: 6,
    descShort: "Arregla tus platos rotos con oro (o algo que brille).",
    descLarge: "Aprende el arte japonés de reparar fracturas con resina y polvo dorado. La filosofía de que lo imperfecto es más bello, ideal para gente que rompe cosas a menudo.",
    randomFact: "Es la excusa perfecta para no admitir que se te cayó la taza favorita de tu madre."
  },
  {
    idExtended: 3,
    city: "Bilbao",
    activity: "Retrato de Mascotas en Acrílico",
    act: "pintura",
    month: "Julio",
    price: "50€",
    center: "Arte Siete",
    places: 10,
    descShort: "Inmortaliza a tu perro antes de que se coma otro zapato.",
    descLarge: "Usaremos técnica de capas y empaste para dar textura al pelaje. No importa si tu gato termina pareciendo un mapache, aquí venimos a divertirnos.",
    randomFact: "Vincent van Gogh nunca pintó a su perro, y mira lo mal que acabó."
  },
  {
    idExtended: 4,
    city: "Bilbao",
    activity: "Tazas con Caras",
    act: "ceramica",
    month: "Septiembre",
    price: "60€",
    center: "Lurra Lab",
    places: 8,
    descShort: "Modelado manual para que tu café te devuelva la mirada.",
    descLarge: "Crearemos tazas antropomórficas desde cero. Aprenderás la técnica del pellizco y cómo añadir elementos realistas a tu vajilla.",
    randomFact: "Si le pones ojos a la taza, te juzgará menos cuando te sirvas el tercer café del día."
  },
  {
    idExtended: 5,
    city: "Bilbao",
    activity: "Lettering sobre Porcelana",
    act: "ceramica",
    month: "Octubre",
    price: "45€",
    center: "Diseño Local",
    places: 12,
    descShort: "Escribe frases motivadoras que no den ganas de llorar.",
    descLarge: "Dominaremos el trazo con rotuladores específicos y horneado doméstico. Ideal para personalizar regalos de Navidad sin gastarte un sueldo.",
    randomFact: "Hacer letras bonitas relaja tanto como gritarle a una almohada, pero es mucho más estético."
  },
  {
    idExtended: 6,
    city: "Madrid",
    activity: "Amigurumis para tu Bebé",
    act: "crochet",
    month: "Mayo",
    price: "48€",
    center: "Lanaterapia",
    places: 8,
    descShort: "Crea un pulpo que no asuste a las visitas.",
    descLarge: "Taller de iniciación al anillo mágico y los puntos básicos. Saldrás con un muñeco blandito y la satisfacción de no haberte pinchado demasiado.",
    randomFact: "Los amigurumis tienen alma, por eso a veces el tuyo parece que te pide ayuda con la mirada."
  },
  {
    idExtended: 7,
    city: "Madrid",
    activity: "Bordado sobre Fotografía",
    act: "textil",
    month: "Junio",
    price: "52€",
    center: "Puntada Brava",
    places: 7,
    descShort: "Dale una segunda vida a tus fotos familiares con hilo.",
    descLarge: "Aprenderás a perforar papel y usar puntos de relieve para añadir flores o marcos a fotos antiguas. Un toque vintage muy moderno.",
    randomFact: "Tu tatarabuela nunca imaginó que terminaría con un pelo rosa bordado en 2026."
  },
  {
    idExtended: 8,
    city: "Madrid",
    activity: "Alfombras de Nudo",
    act: "textil",
    month: "Agosto",
    price: "70€",
    center: "Textil Hub",
    places: 5,
    descShort: "Crea algo suave para que tus pies no toquen el suelo frío.",
    descLarge: "Una técnica clásica que vuelve con fuerza. Ideal para crear tapices de pared o mini alfombras con diseños geométricos y colores pop.",
    randomFact: "Hacer nudos es terapéutico, a menos que se te enrede el hilo en el pelo."
  },
  {
    idExtended: 9,
    city: "Madrid",
    activity: "Crop Top de Verano",
    act: "crochet",
    month: "Julio",
    price: "55€",
    center: "La Tejeduría",
    places: 9,
    descShort: "Teje tu propia ropa antes de que pase la ola de calor.",
    descLarge: "Nivel intermedio. Veremos aumentos, disminuciones y cómo leer patrones sin que parezcan jeroglíficos egipcios.",
    randomFact: "Presumir de que 'lo he hecho yo' aumenta tu autoestima en un 200%."
  },
  {
    idExtended: 10,
    city: "Madrid",
    activity: "Tintes Naturales con Aguacate",
    act: "textil",
    month: "Septiembre",
    price: "58€",
    center: "Eco Tinte",
    places: 10,
    descShort: "Usa la basura de la cocina para teñir tu ropa de rosa.",
    descLarge: "Descubre cómo las cáscaras y huesos de aguacate crean rosas empolvados increíbles. Trae una camiseta blanca vieja y llévate una joya eco.",
    randomFact: "El aguacate sirve para tostadas, para el pelo y para no ir vestido de blanco aburrido."
  },
  {
    idExtended: 11,
    city: "Barcelona",
    activity: "Lettering Divertido",
    act: "manualidades",
    month: "Mayo",
    price: "40€",
    center: "Studio Gràcia",
    places: 15,
    descShort: "Tu letra de médico tiene solución, lo prometo.",
    descLarge: "Dominaremos los rotuladores de punta pincel. Veremos florituras, degradados y cómo hacer que una palabra parezca una obra de arte.",
    randomFact: "El lettering es el arte de dibujar letras, no de escribirlas. Por eso no importa si tienes mala caligrafía."
  },
  {
    idExtended: 12,
    city: "Barcelona",
    activity: "Collage Analógico y Gin",
    act: "manualidades",
    month: "Junio",
    price: "45€",
    center: "The Lab BCN",
    places: 12,
    descShort: "Recorta revistas viejas mientras te tomas algo.",
    descLarge: "Composición visual, teoría del color y pegamento de barra. Una mañana para desconectar del móvil y conectar con las tijeras.",
    randomFact: "En el collage no hay errores, solo 'decisiones artísticas inesperadas'."
  },
  {
    idExtended: 13,
    city: "Barcelona",
    activity: "Pintura Abstracta con Espátula",
    act: "pintura",
    month: "Julio",
    price: "60€",
    center: "Art Space",
    places: 8,
    descShort: "Mancha el lienzo con estilo y finge que eres profesional.",
    descLarge: "Trabajaremos el volumen y la textura usando acrílicos pesados. Aprenderás a perder el miedo al lienzo en blanco y a ensuciarte las manos.",
    randomFact: "La diferencia entre un cuadro abstracto y un manchón es el precio del marco."
  },
  {
    idExtended: 14,
    city: "Barcelona",
    activity: "Creación de Velas con Flores",
    act: "manualidades",
    month: "Octubre",
    price: "50€",
    center: "Candle Bar",
    places: 10,
    descShort: "Haz que tu casa huela a campo y no a perro.",
    descLarge: "Uso de cera de soja, aceites esenciales y flores prensadas. Aprenderás las temperaturas de vertido para que no se te hunda la mecha.",
    randomFact: "Encender una vela hecha por ti te hace sentir un 40% más místico de lo habitual."
  },
  {
    idExtended: 15,
    city: "Barcelona",
    activity: "Customización de Sneakers",
    act: "pintura",
    month: "Noviembre",
    price: "65€",
    center: "Urban Art",
    places: 6,
    descShort: "Dale color a tus zapas blancas aburridas.",
    descLarge: "Técnicas de preparación del cuero, pintura flexible y sellado. Trae tus zapatillas y llévatelas listas para el asfalto.",
    randomFact: "Pintar tus zapatos es la forma más barata de tener una edición limitada de lujo."
  },
  {
    idExtended: 16,
    city: "Valencia",
    activity: "Taller de Torno Express",
    act: "ceramica",
    month: "Mayo",
    price: "75€",
    center: "Barro Vivo",
    places: 4,
    descShort: "Siéntete como en Ghost, pero sin Patrick Swayze.",
    descLarge: "Aprenderás a centrar el barro y levantar tus primeras piezas. Es difícil, es sucio y es extremadamente adictivo.",
    randomFact: "El 90% de las personas que prueban el torno terminan comprándose un delantal profesional esa misma tarde."
  },
  {
    idExtended: 17,
    city: "Valencia",
    activity: "Pendientes de Arcilla Polimérica",
    act: "manualidades",
    month: "Junio",
    price: "38€",
    center: "Joyas de Sol",
    places: 12,
    descShort: "Haz joyas que pesen menos que un suspiro.",
    descLarge: "Mezcla de colores, horneado y montaje de fornituras. Crearás tres pares de pendientes únicos con diseños marmoleados.",
    randomFact: "La arcilla polimérica es básicamente plastilina para adultos con buen gusto."
  },
  {
    idExtended: 18,
    city: "Valencia",
    activity: "Bolsos de Red para el Mercado",
    act: "crochet",
    month: "Julio",
    price: "42€",
    center: "Hilos del Carmen",
    places: 10,
    descShort: "Teje el bolso que aguantará todos tus limones.",
    descLarge: "Ideal para principiantes. Aprenderás el punto red y cómo hacer asas resistentes que no se estiren hasta el infinito.",
    randomFact: "Estas bolsas son ecológicas, modernas y la envidia de cualquier frutería de barrio."
  },
  {
    idExtended: 19,
    city: "Valencia",
    activity: "Macramé: Colgador de Plantas",
    act: "textil",
    month: "Agosto",
    price: "45€",
    center: "Nudo Mix",
    places: 15,
    descShort: "Cuelga tus plantas para que el gato no se las coma.",
    descLarge: "Nudos básicos: plano, alondra y espiral. Saldrás con un colgador boho-chic que hará que tu salón parezca de Pinterest.",
    randomFact: "El macramé es como hacer trenzas, pero sin que nadie se queje de que le das tirones."
  },
  {
    idExtended: 20,
    city: "Valencia",
    activity: "Cerámica con técnica de Plancha",
    act: "ceramica",
    month: "Octubre",
    price: "55€",
    center: "Argila Lab",
    places: 8,
    descShort: "Crea platos que no parezcan ceniceros de guardería.",
    descLarge: "Uso de rodillo y moldes para crear piezas de vajilla plana. Decoración con engobes y texturas naturales.",
    randomFact: "Servir comida en un plato hecho por ti hace que hasta el arroz blanco sepa a estrella Michelin."
  },
  {
    idExtended: 21,
    city: "Sevilla",
    activity: "Pintura de Abanicos Modernos",
    act: "pintura",
    month: "Abril",
    price: "48€",
    center: "Arte al Sur",
    places: 10,
    descShort: "Sobrevive al calor con un abanico diseñado por ti.",
    descLarge: "Aprenderás a pintar sobre tela tensada usando motivos contemporáneos. Nada de tópicos, a menos que tú quieras.",
    randomFact: "Un abanico pintado a mano da un aire de misterio que el aire acondicionado jamás podrá igualar."
  },
  {
    idExtended: 22,
    city: "Sevilla",
    activity: "Encuadernación Copta",
    act: "manualidades",
    month: "Mayo",
    price: "55€",
    center: "Papel y Cartón",
    places: 8,
    descShort: "Haz tu propio cuaderno que se abre 180 grados de verdad.",
    descLarge: "Técnica de cosido visto para crear libretas de artista. Ideal para quienes aman el papel y odian las libretas que se cierran solas.",
    randomFact: "Hacer tu propio cuaderno te da derecho a no escribir nada en él por miedo a estropearlo."
  },
  {
    idExtended: 23,
    city: "Sevilla",
    activity: "Cianotipia sobre Tela",
    act: "textil",
    month: "Junio",
    price: "50€",
    center: "Taller Azul",
    places: 12,
    descShort: "Usa el sol de Sevilla para imprimir tus diseños.",
    descLarge: "Técnica fotográfica antigua que usa la luz UV para crear impresiones en azul Prusia. Usaremos plantas locales para los diseños.",
    randomFact: "Es magia química: pones algo al sol, lo lavas y ¡pum! arte azul."
  },
  {
    idExtended: 24,
    city: "Sevilla",
    activity: "Ilustración con Gouache",
    act: "pintura",
    month: "Septiembre",
    price: "45€",
    center: "Colorín",
    places: 10,
    descShort: "La pintura que parece acuarela pero con superpoderes.",
    descLarge: "Aprenderás la opacidad del gouache, cómo mezclar colores vibrantes y crear ilustraciones con un estilo retro infantil.",
    randomFact: "El gouache es el primo rebelde y opaco de la acuarela que siempre cae bien."
  },
  {
    idExtended: 25,
    city: "Sevilla",
    activity: "Punch Needle (Aguja Mágica)",
    act: "textil",
    month: "Octubre",
    price: "60€",
    center: "Punto y Aparte",
    places: 7,
    descShort: "Borda rápido sin perder la paciencia.",
    descLarge: "La técnica perfecta para ansiosos. Crea texturas de bucle para cojines o cuadros decorativos con lana gorda.",
    randomFact: "Se llama aguja mágica porque el dibujo aparece mientras vas dando 'puñetazos' a la tela."
  },
  {
    idExtended: 26,
    city: "Zaragoza",
    activity: "Upcycling de Chaquetas",
    act: "textil",
    month: "Mayo",
    price: "55€",
    center: "Moda Ética",
    places: 8,
    descShort: "No tires tu chaqueta vieja, ponle parches y arte.",
    descLarge: "Taller de customización. Aprenderás a aplicar telas y pintar sobre denim para que tu ropa sea única.",
    randomFact: "El upcycling es lo que antes llamábamos 'parchear la ropa' pero ahora con mucho más glamour."
  },
  {
    idExtended: 27,
    city: "Zaragoza",
    activity: "Estampación con Sellos de Carvado",
    act: "manualidades",
    month: "Junio",
    price: "40€",
    center: "Grabado Lab",
    places: 10,
    descShort: "Crea tus propios sellos y lánzate a estamparlo todo.",
    descLarge: "Aprenderás a usar las gubias sobre goma y a estampar con tintas textiles. Ideal para personalizar bolsas y camisetas.",
    randomFact: "Una vez que empiezas a hacer sellos, corres el riesgo de estampar hasta el gato."
  },
  {
    idExtended: 28,
    city: "Zaragoza",
    activity: "Mantas de Lana XXL",
    act: "crochet",
    month: "Noviembre",
    price: "85€",
    center: "Big Wool",
    places: 6,
    descShort: "Teje una manta usando tus brazos como agujas.",
    descLarge: "Usaremos lana merino gigante. Es un ejercicio físico y creativo a la vez. Saldrás con una manta de las que quitan el frío de golpe.",
    randomFact: "Si te equivocas de punto, te sirve como saco de dormir provisional."
  },
  {
    idExtended: 29,
    city: "Zaragoza",
    activity: "Decoración de Cestas de Mimbre",
    act: "manualidades",
    month: "Julio",
    price: "45€",
    center: "Cestería Creativa",
    places: 12,
    descShort: "Prepara tu capazo para la piscina con pompones.",
    descLarge: "Aprenderás a coser elementos decorativos y pintar motivos veraniegos sobre fibras naturales.",
    randomFact: "Un capazo con pompones atrae automáticamente las miradas en cualquier playa."
  },
  {
    idExtended: 30,
    city: "Zaragoza",
    activity: "Muralismo para Principiantes",
    act: "pintura",
    month: "Septiembre",
    price: "65€",
    center: "Muro Vivo",
    places: 5,
    descShort: "Pinta paredes sin que te detenga la policía.",
    descLarge: "Escalado de dibujo, uso de botes de spray y pintura plástica en gran formato sobre paneles controlados.",
    randomFact: "El secreto de un buen muralista es saber cuándo dejar de pintar antes de que parezca un garabato gigante."
  },
  {
    idExtended: 31,
    city: "Málaga",
    activity: "Joyas de Cerámica Esmaltada",
    act: "ceramica",
    month: "Mayo",
    price: "52€",
    center: "Barro y Brillo",
    places: 9,
    descShort: "Crea colgantes que no se derritan al sol.",
    descLarge: "Modelado de piezas pequeñas y aplicación de esmaltes de colores vibrantes. Veremos cómo influye el horno en el color.",
    randomFact: "La cerámica es como la cocina: los ingredientes importan, pero el horno manda."
  },
  {
    idExtended: 32,
    city: "Málaga",
    activity: "Bikini de Crochet",
    act: "crochet",
    month: "Junio",
    price: "48€",
    center: "Mar y Lana",
    places: 8,
    descShort: "Teje el bikini que no se te caerá en la primera ola.",
    descLarge: "Veremos puntos tupidos y cómo poner forros para que el crochet sea funcional en el agua. Nivel intermedio.",
    randomFact: "Un bikini tejido a mano es la prueba definitiva de paciencia veraniega."
  },
  {
    idExtended: 33,
    city: "Málaga",
    activity: "Vajilla con Estampación de Hojas",
    act: "ceramica",
    month: "Septiembre",
    price: "58€",
    center: "Taller Mediterráneo",
    places: 10,
    descShort: "Usa hojas reales para decorar tus platos.",
    descLarge: "Técnica de impresión sobre barro fresco. Usaremos hojas de higuera y parra para dejar texturas hiperrealistas.",
    randomFact: "Es la forma más elegante de llevarte el jardín a la mesa del comedor."
  },
  {
    idExtended: 34,
    city: "Málaga",
    activity: "Atrapasueños de Ganchillo",
    act: "crochet",
    month: "Agosto",
    price: "40€",
    center: "Nudos Marinos",
    places: 15,
    descShort: "Caza pesadillas con mandalas de lana.",
    descLarge: "Aprenderás a tejer en circular y a decorar el aro con plumas y cuentas. Muy relajante.",
    randomFact: "Si no atrapa sueños, al menos decora la pared de forma espectacular."
  },
  {
    idExtended: 35,
    city: "Málaga",
    activity: "Kokedamas de Barro",
    act: "manualidades",
    month: "Octubre",
    price: "45€",
    center: "Green Art",
    places: 12,
    descShort: "Plantas que flotan en bolas de musgo y arcilla.",
    descLarge: "Aprenderás a crear el sustrato perfecto y a envolver las raíces para que tu planta viva feliz sin maceta.",
    randomFact: "Las kokedamas son como las mascotas, pero no ladran ni necesitan que las saques a pasear."
  },
  {
    idExtended: 36,
    city: "Santiago",
    activity: "Acuarela de Lluvia",
    act: "pintura",
    month: "Noviembre",
    price: "45€",
    center: "O Taller",
    places: 10,
    descShort: "Aprovecha que llueve para pintar paisajes brumosos.",
    descLarge: "Técnica húmedo sobre húmedo. Aprenderemos a crear atmósferas grises y verdes típicas de Galicia.",
    randomFact: "En Santiago, si no llueve mientras pintas, la acuarela no queda igual de auténtica."
  },
  {
    idExtended: 37,
    city: "Santiago",
    activity: "Talla de Sellos de Madera",
    act: "manualidades",
    month: "Mayo",
    price: "60€",
    center: "Madeira Viva",
    places: 6,
    descShort: "Corta madera sin perder ningún dedo.",
    descLarge: "Iniciación a la xilografía básica para estampar en papel. Uso de gubias profesionales y tintas de grabado.",
    randomFact: "Oler a madera recién cortada es mejor que cualquier ambientador de pino."
  },
  {
    idExtended: 38,
    city: "Santiago",
    activity: "Linograbado Botánico",
    act: "manualidades",
    month: "Junio",
    price: "50€",
    center: "Estampa Galega",
    places: 8,
    descShort: "Crea tu propia serie de láminas artísticas.",
    descLarge: "Dibujo, tallado en linóleo y estampación manual con baren. Te llevarás 5 copias numeradas de tu diseño.",
    randomFact: "El linograbado es como hacer un sello, pero para gente que quiere sentirse artista de galería."
  },
  {
    idExtended: 39,
    city: "Santiago",
    activity: "Pintura de Paisaje con Café",
    act: "pintura",
    month: "Abril",
    price: "35€",
    center: "Café Arte",
    places: 15,
    descShort: "Si no te lo bebes, píntalo.",
    descLarge: "Uso del café como pigmento monocromático. Veremos diferentes concentraciones para lograr sombras sepia.",
    randomFact: "Es la técnica más barata del mundo: solo necesitas un pincel y un expreso doble."
  },
  {
    idExtended: 40,
    city: "Santiago",
    activity: "Libro de Artista Textil",
    act: "textil",
    month: "Octubre",
    price: "65€",
    center: "Fíos e Papel",
    places: 7,
    descShort: "Un diario donde las páginas son de tela.",
    descLarge: "Combinaremos retales, bordado libre y transferencia de imágenes para crear un libro objeto único.",
    randomFact: "Un libro de artista es un diario secreto que puedes enseñar a todo el mundo sin que entiendan nada."
  }
];